<?php

namespace Database\Seeders;

use App\Models\Kurator;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class KuratorSeeder extends Seeder
{
    public function run(): void
    {
        $kuratorlar = [
            "Abdunazarov O'ktam Qushoqvich",
            "Bazarov Sobirjon Bektoshevich",
            "Salomov G'ulom Yuldoshevich",
            "Pardayev Alisher Ochilovich",
            "Xayitova Firuza Abdullayevna",
            "Abdunabiyev Hikmatulla Exsonovich",
            "Yuldashev Elyor Abdusalom o'g'li",
            "Bekpo'latova Anora",
            "Nematullayev Nodir Muzaffar o'g'li",
            "Choriyev Ulug'bek Normeyliyevich",
            "O'ralova Oysuluv Poyonovna",
            "Berdimurodova Sevara Mahmudovna",
            "Sohibova Dilnoza Ergashovna",
            "Qodirova Sarvinoz Ravshan qizi",
            "Saydullayev Farrux Umedulla o'g'li",
            "Ro'zimurodova Shohista Akbar qizi",
            "Aminova Dilnoza Orifjonovna",
            "Axmedov Erkin Qurbonovich",
            "Jumayeva Shohida Choriyevna",
            "Norqulova Shaxnoza To'lqinovna",
            "Boysoatov Muzaffar Bo'ri o'g'li",
            "Abdurahmonov Azamat Ostonaqulovich",
            "Tangirov Ro'ziboy Xudoyshukurovich",
            "Mingnarova Maftuna Toshboy qizi",
            "Xolmurodova Shoxista Mirzaliyevna",
            "Xudoyorova Gulnora Nuriddinovna",
            "Sattarova Yelena Anatolyevna",
            "Jabborova Nargiza Islomjonovna",
            "Kurbanova Nazira Nizomiddinovna",
            "Jumayev Otabek Alisher o'g'li",
            "Begimqulov Oltiboy Jo'rayevich",
            "Boboqulov Chori O'rolovich",
            "Toshova Shaxnoza Tojinorovna",
            "Mengto'rayeva Umida Anvar qizi",
            "Narboshova Maqsuda Ochilovna",
            "Nazarov Otabek Muzrobovich",
            "Abdurahmonov Akmal Yuldoshovich",
            "Fayzullayeva Mavlyuda Xamzayevna",
            "Qalandarov Qalandar Abdurahimovich",
            "Ochilova Aziza Alisher qizi",
            "Mengnarov Abdullo Xolmo'min o'g'li",
            "Bo'riyeva Shaxnoza G'ofur qizi",
            "Shoyimova Komila O'ral qizi",
            "Mingboyev Otabek Alijon o'g'li",
            "Bo'riyeva Muxayyo Shavkatovna",
            "Toshpo'latov Akmal Xolmirzayevich",
            "Qurbonova Shahlo Salomovna",
            "Bo'riyev Sardor Bobur o'g'li",
            "Panjiyev Suhrob",
            "Tojiyev Husniddin Baxtiyorovich",
            "Habibullayeva Shoira Shukrullayevna",
            "Omonova Nilufar Omon qizi",
            "Xayrullayeva Larisa Erkin qizi",
            "Azizjonova Asilabonu Alisher qizi",
            "Jumayev Ilhom Hamroyevich",
            "Avliyoqulov Tolib Xolmurodovich",
            "Nurmamatov Abdumalik Shermatovich",
            "Rahmonqulova Feruza Umidullayevna",
            "Chorshanbiyev Anvar Allaberdi o'g'li",
            "Qoraqulov Azizbek Amanqulovich",
            "Bakirov Juma Ashurovich",
            "Xurramova Dilso'z Baxtiyor qizi",
            "Xurramova Mohidil Baxtiyorovna",
            "Eshqorayev Ulug'bek Choriyevich",
            "Safarova Dilorom Abdikadirovna",
            "Qosimov Abdusattor Choriyevich",
            "Karimov Abdulaziz Nurullayevich",
            "Mengliqulova Manzura Abdullayevna",
            "Shodiyeva Nodira Normamatovna",
            "Po'latov Muhriddin Qo'zimuradovich",
            "Aslanova Xolida Gaffurovna",
            "Kibriyev Behro'z Abdurahmonovich",
            "Ochilova Dilorom Abdukarimovna",
            "Bo'riyeva Dilnoza Baxriddinovna",
            "Ro'ziyev Oybek Avlayevich",
            "Choriyev Abubakir Chorshamiyevich",
            "Chorshanbiyev Chori Xudaymuradovich",
            "Shermatov Xolbek Fahriddinovich",
            "Yarov Umidullo Azamovich",
            "Husanov Sayidbek Almat o'g'li",
            "Aminqulov Shaxrijahon O'tkir o'g'li",
            "Abdusamiyeva Nargiza Qudrat qizi",
            "Sultonov Ravshan Komiljonovich",
            "Xaitov Akmal Alyarovich",
            "Saidov Xusniddin Shamsiddin o'g'li",
            "Xalbayeva Zarina Kaxramanovna",
            "Qurbonova Gulnoza Abduraim qizi",
            "Alimova Zebiniso Farxodjon qizi",
            "Saidov Jasur Baxtiyorovich",
            "Babamuratov Bekzod Ergashevich",
            "Ibragimova Gulmira Rashidovna",
            "Ko'charova Ma'mura Faxriddin qizi",
            "Hazratqulova Ozoda Abduganiyevna",
            "Xolboyev Norbek Aliniyozovich",
            "Tursunov Quvochbek Nasim o'g'li",
            "Axmedov Ulug'bek Xolbekovich",
            "Eshqobilov Ozodbek Abdusodiqovich",
            "Kenjayev Yodgor Mamatqulovich",
            "Xudoyqulova Zebo Ravshanovna",
            "Babamurodov Alisher Ruzibayevich",
            "Buzrukov To'lqin Omonovich",
            "Qayumova Shaxnoza Jamshidovna",
            "Voxidova Dilfuza Farxodovna",
            "Ko'chkeldiyeva Shaxnoza Chorshanbiyevna",
            "Chariyev Muzaffarbek Yuldashevich",
            "Soatova Zarina Akbarovna",
            "Kibriyeva Maxfirat Abduraxmonovna",
            "Sultonov Sirojiddin Nuraliyevich",
            "Tojimurodov Mansur Tojimurodovich",
            "Raimov Shaxboz Qurbonmuratovich",
            "Ziyodullayeva Leyla Ibrohimovna",
            "Xolmurodov Inoyatullo Ismatulloyevich",
            "Bo'riyev Muhammadali G'ayrat o'g'li",
            "Xolliyeva Mohigul Ravshanovna",
            "Umirqulova Feruza Absamatovna",
            "Tog'ayev Azizbek Aliyor o'g'li",
            "Jo'rayev Sanjar Ramazonovich",
            "Turayev Xayrulla Erkin o'g'li",
            "Boyqobilov Soatmurod Shuxrat o'g'li",
            "Meyliyev Zohid Shavkat o'g'li",
            "Bekmirzayev Eshquvvat Ro'ziboyevich",
            "Ro'ziyeva Gulsara Temirqulovna",
            "Tashpulatov Tulqin Aliyarovich",
            "Annayev Umidjon Faxriddinovich",
            "Jo'rayev Zoxidjon Ashurovich",
            "Mamadiyeva Zarifa Norboyevna",
            "Pardayev Anvar Misirovich",
            "Pardayev Otabek Anvarovich",
            "Hayitova Mehrigul Alijon qizi",
            "Xaitova Saida Xasanovna",
            "Boyqulov To'rabek Temirovich",
            "Rasulov Abdusamat Abdujabborovich",
            "Ergashev Navro'zbek Allanazar o'g'li",
            "Xamroyev Rashid Ravshan o'g'li",
            "Tillayeva Zarina Zafarbekovna",
            "Badalov Dilmurod Abduxalilovich",
            "Zokirov Javohir G'aybulla o'g'li",
            "Abdusamatov Alisher Sobirovich",
            "Eshboyeva Surayyo Qahramon qizi",
            "Babayeva Maxfuza Abduvoitovna",
            "Jabborova Subhida Abdullayevna",
            "Solixova Xumora Xasan qizi",
            "Norqobilova Nigora Uralovna",
            "Ismoilov Bobur Toxirovich",
            "Almardonova Iroda Toshmamatovna",
            "Turobova Sevara Kattaqulovna",
            "Ergasheva Rayhon O'tkirovna",
            "Bobomurodova Shoira Erkinovna",
            "Mahmadiyeva Gulchehra Said-Abdullayevna",
            "Xonova Dilrabo Baratovna",
            "Babayev Anvar Ahmedovich",
            "Salimov O'tkir Saydullayevich",
            "Qarshiyeva Iroda Baxtiyarovna",
            "Almardanov Jo'rabek Bobonazarovich",
            "Karimov Akbar Ortiqovich",
            "Xamrayeva Ra'no Rajabovna",
            "Xolov Olim Chorshamiyevich",
            "Jumayeva Gulnora Tursunpo'latovna",
            "Yormatova Faxriddin Jaylovovich",
            "Eshqurbonov Sirojiddin Bozorovich",
            "Mingboyev Azizbek Alijon o'g'li",
            "Davlyatova Matlyuba Xolmuminovna",
            "Mukumova Dilafruz Ziyodullayevna",
            "Mustafaqulova Zarifa Baxodir qizi",
            "Djumayeva Dildora Isroilovna",
            "Tashbayeva Ugilshod Abduvaxidovna",
            "Saloxitdinova Navro'za Muradulla qizi",
            "Xaydarova Mahliyo Habibullayevna",
            "Amirqulova Zebiniso Mustafaqulovna",
            "Toshpulatova Niyoxon Shavkatjon qizi",
            "Begaliyeva Mexriniso Olimnazarovna",
            "Jo'rayeva Gavhar Eshqobilovna",
            "Rahimova Shahzoda Do'stmurodovna",
            "Yodgorova Sitora Bahromovna",
            "Usmonov Mansur Qurbonmurotovich",
            "Turayeva Gulnoza Ergashevna",
            "Xujamqulova Iroda Faxriddin qizi",
            "Oltiboyeva Kamola Sharofjon qizi",
            "Qosimov Botir Saidvali o'g'li",
            "Xudayberdiyeva Xuriyat Karimberdiyevna",
            "Narmuratov Zayniddin Radjabovich",
            "Xaitov Abduqosim Abdulakim o'g'li",
            "Tursunov Nurullo Narzullayevich",
            "Tursunov Anvar Saypullayevich",
            "Tursunov Uktam Sayfullayevich",
            "Kabilov Kamoliddin Eshboltayevich",
            "Muxammadiyeva Dinora Tursunpulatovna",
            "Badalov Kamoliddin Rahmat o'g'li",
            "Jo'rayev Atham Qoraqulovich",
            "Madiyeva Madina Yusupovna",
            "Allayev Zafar Mingboyevich",
            "Suleymanov Damir Nazinovich",
            "Kamolov Umid Achilovich",
            "Salomova Gavhar Abdunazarovna",
            "Raimov Lazizjon Alisherovich",
            "Umurzakova Bonuxon Azizovna",
            "Kayumova Shaxnoza Kobiljonovna",
            "Tairova Mahfuza Abdusattarovna",
            "Almardonova Ra'no Norboyevna",
            "Norqobilova Rayxon Davlatovna",
            "Tojiboyeva Shohistaxon Komiljonovna",
            "Muqimov Mahmud Xudoyberdiyevich",
            "Erdonova Muxlisa Xoshim qizi",
            "Ibodullayeva Dinara Baxramjanovna",
            "Shonazarova Sevara Rashidovna",
            "Jabborov Faxriddin Alisherovich",
            "Masodiqova Hilola Bahromjon qizi",
            "Toshov Kamoliddin Tojinorovich",
            "Bekmirzayev Shavkat Olim o'g'li",
            "Ro'ziyeva Mashhura Abdumo'minovna",
            "Rahmonov Botir Abdurasulovich",
            "Yarmatov Sharofiddin Choriyevich",
            "Xurramov Nosir Xamidovich",
            "Toyirov Akbar Xasanovich",
            "Begaliyev Azizjon Olimnazarovich",
            "To'xtayeva Nazokat Rustamovna",
            "Ernazarov Mirzohid Yuldash o'g'li",
            "To'rayev Dilmurod Shokir o'g'li",
            "Turayev Ziyadulla Norsoatovich",
            "To'rayev Baxtiyor Ergashevich",
            "Boboxonov Muhammadaziz Shavkatovich",
            "Ziyodullayev Sodiqjon Mamadillayevich",
            "Xakimov Zafar Ibragimovich",
            "Xurramov Ramazon Allayor o'g'li",
            "Namazov G'afur Shokulovich",
            "Shodiev Akbar Ashurovich",
            "Erdonayev Bunyodjon Abdimalikovich",
            "Ergashev Akmal Abdurasul o'g'li",
            "Abduraimova Nigora Abdugapparovna",
            "Xushbaqov Baxodir Abdulazizovich",
            "Pardayev Anvar Yusupovich",
            "Mamadjanova Tuygʻunoy Axmadjanovna",
            "Pardayev Lochinbek Farxod o'g'li",
            "Amonov Mexriddin Oromiddinovich",
            "Xaydarova Shoxista Davronovna",
            "Rashidova Xadicha Tursunaliyevna",
            "Xolmatova Asila Menglimurod qizi",
            "Ismatov Sharofiddin Asatullayevich",
            "Muzropova Shahnoza Saydullayevna",
            "Avliyaqulov Ashurali Avazovich",
            "Eshqulova Nasiba Normurodovna",
            "Bobamuratov Ulug'bek Erkinovich",
            "Xayrullayev Ismatulla Nurullayevich",
            "Xoliyarov Erkin Chorshanbiyevich",
            "Sattarov Abduvali Umirqulovich",
            "Qosimov Odilbek Yunusovich",
            "Abdusamatov Mamayusuf Kulmanovich",
            "Oltiboyeva Feruza Ulug'bek qizi",
            "Yusupov Gulboy Amirovich",
            "Saparov Ismat Chorshanbiyevich",
            "Do'stmuhamedova Nozima Xamidullo qizi",
            "Eshniyozov Asadbek Abdinazar o'g'li",
            "Mo'minova Mavjuda Sharifovna",
            "Xudoyorova Zuxra Yuldashovna",
            "Shoimqulov Asror Abdunabiyevich",
            "Odilov Umid Abduxalimovich",
            "Absamatov Asqar Ergashovich",
            "Kinjayev Kattaqul Nurmatovich",
            "Jurayev Husan Atamurodovich",
            "Raxmatullayev Bobir Chorshamiyevich",
            "Xayitmurodova Gulnoza To'ra qizi",
            "Nurislomova Latofat Fazliddinovna",
            "Abdurahmanova Feruza Fahriddin qizi",
            "Choriyeva Muattar Sharof qizi",
            "Erdonov Bekmurod Xolboy o'g'li",
            "Ishmuratov Baxodir Xusanovich",
            "Jo'rayeva Safargul Nurullo qizi",
            "Nomozova Rayhona Rustamovna",
            "Panjiyeva Nazokat Normaxmatovna",
            "Ramazanov Xusniddin Saidaxmadovich",
            "Raximov Furqat Rashid o'g'li",
            "Shukurov Sherzod Xolmo'min o'g'li",
            "To'qsonov Xurshid Egamberdiyevich",
            "Uzmanov Ixtiyor Ibragim o'g'li",
            "Ismoilova Sabina Erkin qizi",
            "Mamarajabov G'ayrat Abdulxakimovich",
            "Saidmurodov Asliddin Dilmurod o'g'li",
            "Mahmatrayimov Shahzod Qo'shshoq o'g'li",
            "Odinayev Abduvohid Shuhrat o'g'li",
            "Abrayeva Sevara Toshtemirovna",
            "Buriyev Javoxir Nosir o'g'li",
            "Avazova Elsevar Erkinovna",
            "Abrayev Baxrom Xolto'rayevich",
            "Qodirov Xasan Do'stqobilovich",
            "Jumayev Azamat Qurbonali o'g'li",
            "Abdurahimov Sarvar Nasrilloyevich",
            "Turdialiyev Fahriddin Djo'rayevich",
            "Muradova Ra'no Anvarovna",
            "Xurramov Ruslan Erkin o'g'li",
            "Shonazarova Gulnoza Shuxrat qizi",
            "Ibragimov Aziz Ilhomovich",
            "Raupova Navbahor Bahriddinovna",
            "Misirova Nozanin Nurullo qizi",
        ];

        foreach ($kuratorlar as $index => $fullName) {
            $nameParts = explode(' ', trim($fullName));
            $familiya = $nameParts[0] ?? '';
            $ism = $nameParts[1] ?? '';

            $emailBase = $this->transliterate(strtolower($familiya . '_' . $ism));
            $email = $emailBase . '_' . ($index + 1) . '@tisu.uz';

            $user = User::create([
                'name' => $fullName,
                'email' => $email,
                'password' => Hash::make('password123'),
                'role' => 'kurator',
            ]);

            Kurator::create([
                'user_id' => $user->id,
                'details' => [
                    'room' => 'A-' . rand(100, 500),
                    'phone' => '+99891' . rand(1000000, 9999999),
                    'full_name' => $fullName,
                ],
            ]);
        }
    }

    private function transliterate(string $text): string
    {
        $replacements = [
            'o\'' => 'o',
            'o`' => 'o',
            'oʻ' => 'o',
            'g\'' => 'g',
            'g`' => 'g',
            'gʻ' => 'g',
            'sh' => 'sh',
            'ch' => 'ch',
            'x' => 'x',
            'q' => 'q',
            '\'' => '',
            '`' => '',
            'ʻ' => '',
            'ʼ' => '',
            ' ' => '_',
        ];

        $text = str_replace(array_keys($replacements), array_values($replacements), $text);
        $text = preg_replace('/[^a-z0-9_]/', '', $text);
        $text = preg_replace('/_+/', '_', $text);

        return trim($text, '_');
    }
}
